FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive

# 更新包列表并安装依赖项
RUN apt-get update && apt-get install -y \
    build-essential \
    libeigen3-dev \
    wget \
    zip \
    git \
    tar \
    cmake \
    g++ \
    libx11-dev \
    libglew-dev \
    libgl1-mesa-dev \
    libosmesa6-dev \
    libglfw3-dev \
    libxinerama-dev \
    libxcursor-dev \
    libxi-dev \
    libssl-dev \
    unzip && \
    x11-apps \
    xvfb \
    mesa-utils \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /root/PNDbotics/

# 拷贝文件
COPY ./pnd_adam_deploy_public.zip ./
RUN unzip pnd_adam_deploy_public.zip && rm pnd_adam_deploy_public.zip

CMD ["xpra", "start", "--bind-tcp=0.0.0.0:14500", "--html=on", "--start=xterm"]